### ISSUE TITLE
Test data not working

### ISSUE THREAD

**Issue by janka2012** [xiezhq/ISEScan#10]
Hi, I am trying to run ISEScan using the testing data you have provided with the tool (NC_012624 genome). Unfortunatelly I am getting this weird error message. Do you have any suggestion what could cause this error? Many thanks.

gi|228288719|ref|NC_012624.1| generated an exception: [Errno 13] Permission denied
Begin addNonORFcopy at Fri Apr  5 12:04:45 2019
Traceback (most recent call last):
  File "isescan.py", line 56, in <module>
    isPredictSingle(args4isPredictSingle)
  File "isescan.py", line 21, in isPredictSingle
    isPredict.isPredict(filelist, path2proteome, path2hmm)
  File "/mnt/storage-brno6/home/xputer00/ISEScan-1.6/isPredict.py", line 282, in isPredict
    pred.pred(args4pred)
  File "/mnt/storage-brno6/home/xputer00/ISEScan-1.6/pred.py", line 2604, in pred
    mOrfHits = addNonORFcopy(mispairs, mOrfHits)
  File "/mnt/storage-brno6/home/xputer00/ISEScan-1.6/pred.py", line 1956, in addNonORFcopy
    if len(copypairs[seqid]) == 0:
KeyError: 'gi|228288719|ref|NC_012624.1|'

**Comment by janka2012** [comment]
I figured out that blast was missing in my $PATH.
