### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by a1204350** [xiezhq/ISEScan#2]
Begin addNonORFcopy at Fri Aug  4 16:00:11 2017
Traceback (most recent call last):
  File "isescan.py", line 57, in <module>
    isPredictSingle(args4isPredictSingle)
  File "isescan.py", line 22, in isPredictSingle
    isPredict.isPredict(filelist, path2proteome, path2hmm)
  File "/home/zong/programs_and_scripts/ISEScan/ISEScan-master/isPredict.py", line 282, in isPredict
    pred.pred(args4pred)
  File "/home/zong/programs_and_scripts/ISEScan/ISEScan-master/pred.py", line 2604, in pred
    mOrfHits = addNonORFcopy(mispairs, mOrfHits)
  File "/home/zong/programs_and_scripts/ISEScan/ISEScan-master/pred.py", line 1956, in addNonORFcopy
    if len(copypairs[seqid]) == 0:
KeyError: 'SWU01_chr'

The example worked fine, but when I used my own sequence (a complete bacterial chromosome) it failed as above. Could you please help me with this? Thanks much

**Comment by xiezhq** [comment]
Sorry to respond late. I didn't check my github site every day.  Could you send me your sequence file in fasta format? Or you can put somewhere to let me download it.

Best,
Zhiqun Xie

**Comment by dtravisany** [comment]
Hello, I had the same error. I think that could be related with blast warning "/lib64/libz.so.1: no version information available" or with different (more than one) python installation.
To fix this issue, I add the path of my condas lib to LD_LIBRARY_PATH
Example:
 export LD_LIBRARY_PATH=/path_to_anaconda/lib:$LD_LIBRARY_PATH

Cheers,
Dante

**Comment by xiezhq** [comment]
Good points, Dante. Thanks for your comments in ISEScan.

Best,
Xie
