### ISSUE TITLE
UnboundLocalError: local variable 'seqid' referenced before assignment 

### ISSUE THREAD

**Issue by IRSINGH27** [xiezhq/ISEScan#46]
ISEScan starts at Tue Aug 23 17:43:29 2022
use NCBI protein database

command : 
`isescan.py --seqfile GCF_013415905.1_ASM1341590v1_genomic.gbff --output result/ --no-FragGeneScan`

```
Traceback (most recent call last):
  File "/home/aswin/irsingh/miniconda3/envs/isescanner/bin/isescan.py", line 87, in <module>
    isPredictSingle(args4isPredictSingle)
  File "/home/aswin/irsingh/miniconda3/envs/isescanner/bin/isescan.py", line 25, in isPredictSingle
    isPredict.isPredict(filelist, args['output'], args['removeShortIS'], args['translateGenome'],
  File "/home/aswin/irsingh/miniconda3/envs/isescanner/bin/isPredict.py", line 208, in isPredict
    proteome_files = proteinFromNCBI(dnaFiles, path_to_proteome)
  File "/home/aswin/irsingh/miniconda3/envs/isescanner/bin/isPredict.py", line 195, in proteinFromNCBI
    tools.gbk2fgs4protein(fnaFile, gbkFile, fgsFile)
  File "/home/aswin/irsingh/miniconda3/envs/isescanner/bin/tools.py", line 1450, in gbk2fgs4protein
    seqid = rdGbFna(fnaFile)
  File "/home/aswin/irsingh/miniconda3/envs/isescanner/bin/tools.py", line 1298, in rdGbFna
    return seqid
UnboundLocalError: local variable 'seqid' referenced before assignment
```

**Comment by xiezhq** [comment]
Hi,

ISEScan does not support using NCBI protein database. The option '--no-FragGeneScan' does not make much sense.

Xie
